version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: "Dockerfile-frontend"
    ports:
      - "9000:80"
    links:
      - backend  
  backend:
    build:
      context: .
      dockerfile: "Dockerfile-backend"
    ports:
      - "8083:80"
    links:
      - mssql  
  mssql:
    build:
      context: .
      dockerfile: "Dockerfile-mssql"
    ports:
      - "1433:1433"